#version 460

#extension GL_GOOGLE_include_directive: require
#include "ants_struct.glsl"

layout(constant_id = 0) const uint ANT_COUNT = 1;

layout(binding = 0) buffer AntBuffer {
	Ant ants[];
};

#include "ants_functions.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	if (!is_valid_ant(gl_GlobalInvocationID.x)) return;
	clear_ant(gl_GlobalInvocationID.x);
}
